### ISSUE TITLE
Learn GitHub layout/features (Explore the interface, understand the interface)

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#11]

**Comment by computerbluerain** [comment]
Hi Nate,

Thank you so much!


Best Regards,

Patrice Terrell

**Comment by natt96z** [comment]
**_Please also screenshot completed milestones and post them in the CyberChat via Signal!_**

Have fun! Start with the file structure if you want.

**Comment by natt96z** [comment]
Completed over Zoom December 2022
