### ISSUE TITLE
Nate's Task (10/2/23 - 10/13/23)

### ISSUE THREAD

**Issue by liluzibird** [natt96z/cybersac#121]
- Media department testimonials (WIP/Pending)
- Still Try to Reach MSA-Santa Ana 
- Zoom Meeting Thursday 3:30PM 
- Spell Check - Review Student Feedback (CyberSAC Material)
- Improve Current and Future Material (OneDrive Material)
-----------------------------------------------------------------------------------------------------------------
Still make phone calls if there is a possible extension to additional schools. We have a meeting this Thursday on Zoom at 3:30, we are going to possibly discuss team virtual machine and school scheduling.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/5ac5edef-4f04-486d-a75c-5e8479a2e783)

**Monday October 2nd, 2023** - Me and @userliluzibert visited Magnolia Science Academy to talk to Mr. K, Mr Quarez and the computer department, we were given a tour of the school, I CC'd all completed work to the appropriate party. We were then shown the schools computer hardware and later led into the Principals conference room to complete registration.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/af896f0d-da2c-4db0-a212-abac4603c548)

**Tuesday October 3rd, 2023** - I followed up with Mr Juarez this day to make sure he has team members picked and isn't having any issues with the website, we reviewed certain cyber material and concluded there was a slight verification issue with his account created, issue is in progress being fixed.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/ff3230ce-9fe7-4c23-adf2-02a7f6a628f1)

Wednesday October 4th 2023 - Code Cleanup, sites themes configuration was updated again to fix loading bucks and compile issues. Website version is now 5.0.1. With help from team mate @userliluzibert we had to add a new _themes directory to github and update the api theming engine to the latest RTD version for strange security reasons.

**Comment by natt96z** [comment]
![Screenshot from 2023-10-05 16-55-43](https://github.com/natt96z/cybersac/assets/112590005/d9354404-31bc-45bf-a879-7cac34ca436a)

**Thursday October 5th** - Zoom Meeting with group, we discussed the MSA visit, future school prospects and adding quality of life improvements to the team website. There is a possible issue with MSA enrollment thats in progress of being fixed.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/e4d92949-ccc1-412d-876c-87055fb1cae9)
![image](https://github.com/natt96z/cybersac/assets/112590005/83bc5f03-30aa-4e28-abac-98d27dd762df)
![image](https://github.com/natt96z/cybersac/assets/112590005/b8882271-5b1e-4b9a-9791-bff58ecc11cd)

**10/09/2023-10/10/2023** Talked with CyberPatriot Tech Support line  at 7AM for around 30 minutes to help guide me through how to solve the registration issue, I was informed to use the info@cyberpatriots email as verifier if principal email did not work. She mentioned that they did however provide the VM tools in an email, I mentioned the school I was trying to register etc. So I reviewed that material as well. Emails were also sent out and CC'd tuesday the 10th regarding this as well. (as well as texted as well)

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/6b2d949c-51d3-4db6-b51a-066bf01518fa)

**10/11/2023 - Me,Patrice and Albert** reviewed Alicias OneDrive that was sent over the school email, as a team we also made sure content was relatable to what we already had on cybersac and powerpoint material improvements as well. Another followup email was sent to MSA with Albert's help in the process as well emailing them.

**Comment by natt96z** [comment]
![Screenshot from 2023-10-12 15-03-16](https://github.com/natt96z/cybersac/assets/112590005/eabac85f-ce89-478c-8457-48dc15b425d8)
![Screenshot from 2023-10-05 16-11-41](https://github.com/natt96z/cybersac/assets/112590005/6e4e7060-0c3d-476c-b8ce-88c0f3bc10b5)


11/12/2023 - Me and Mr Juarez attempted to fix registation issue and now its set at pending still regardless, so I requested him still send me the info on the gathered students for the even. Mr K already chose 5 students so far and that info should be avaliable later Friday afternoon as requested. A zoom meeting with the group was also held regarding communication with schools and updates.
