### ISSUE TITLE
Patrice's Task (10/9/23-10/13/23)

### ISSUE THREAD

**Issue by liluzibird** [natt96z/cybersac#122]
- Media department testimonials (WIP/Pending)
- Reach Out To Garden Grove School 
- Zoom Meeting Thursday 3:30PM 
- Spell Check - Review Student Feedback (CyberSAC Material)
- Improve Current and Future Material (OneDrive Material)
-----------------------------------------------------------------------------------------------------------------
Still make phone calls if there is a possible extension to additional schools. We have a meeting this Thursday on Zoom at 3:30, we are going to possibly discuss team virtual machine and school scheduling.

**Comment by natt96z** [comment]
![Screenshot from 2023-10-05 16-55-43](https://github.com/natt96z/cybersac/assets/112590005/d9354404-31bc-45bf-a879-7cac34ca436a)

**Thursday October 5th** - Zoom Meeting with group, we discussed the MSA visit, future school prospects and adding quality of life improvements to the team website. There is a possible issue with MSA enrollment thats in progress of being fixed.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/a891b716-27c0-4141-bf0d-471768cfc44a)
![image](https://github.com/natt96z/cybersac/assets/112590005/7f1faaf1-ef08-44ad-a285-6291b614f37d)

**Monday October 9th** - Review CyberSAC Site and OneDrive: Reordganized and moved files to the appropriate directories, certian files were not organized and placed in the proper folders and sharing features have been fixes and well, spell check was also completed on the site as usual after @userliluzibert and @natt96z fixed sitewide loading issues. Feedback is what led to future improvements.

**Comment by computerbluerain** [comment]
10/9/2023 - Emails to Myra Clarke from Garden Grove High School

![GGHEmail1](https://github.com/natt96z/cybersac/assets/116924471/2a29673b-362e-4b99-b4c1-67e366f2b7e3)

10/12/2023 - Replied to another Email for Myra Clarke from Garden Grove High School
![GGHEmail4](https://github.com/natt96z/cybersac/assets/116924471/14162914-a0f5-4afc-8954-05df161e8fb4)
![GGHEmail2](https://github.com/natt96z/cybersac/assets/116924471/7019a7f3-5c96-42cf-ac11-538592c4d351)

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/6b2d949c-51d3-4db6-b51a-066bf01518fa)

**10/11/2023 - Me, Nate and Albert** reviewed Alicias OneDrive that was sent over the school email, as a team we also made sure content was relatable to what we already had on cybersac and powerpoint material improvements as well. Another followup email was sent to MSA with Albert's help in the process as well emailing them.

**Comment by natt96z** [comment]
![Screenshot from 2023-10-05 16-11-41](https://github.com/natt96z/cybersac/assets/112590005/914349c5-79d3-44a9-a1f6-abdbc9441580)

**10/12/2023 - A zoom meeting with the group** was also held regarding communication with schools and updates. We worked on improving out emails, how to solve registration issues and our next step studying the official competition material together. We understand practice round is coming to an end but we are getting cooperation from these schools at the same time.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/c96be73d-6ef1-42da-be44-b1bf101cf268)

**10/11/2023 Reached out to Myra Clarke** of Garden Grove regarding the Cyberpatriot competition, more information on that email and call interaction will be added as well. Professor Jason had gotten a response email over the subject as well.
