### ISSUE TITLE
Angel's Task (10/9/23-10/13/23)

### ISSUE THREAD

**Issue by liluzibird** [natt96z/cybersac#123]
- Media department testimonials (WIP/Pending)
- Work at Valley High School - Mentorship
- Zoom Meeting Thursday 3:30PM 
- Spell Check - Review Student Feedback (CyberSAC Material)
- Improve Current and Future Material (OneDrive Material)
-----------------------------------------------------------------------------------------------------------------
Still make phone calls if there is a possible extension to additional schools. We have a meeting this Thursday on Zoom at 3:30, we are going to possibly discuss team virtual machine and school scheduling.

**Comment by natt96z** [comment]
![image](https://github.com/natt96z/cybersac/assets/112590005/5ad3935d-3f4c-452a-a296-3c407e858d62)
![image](https://github.com/natt96z/cybersac/assets/112590005/0c657300-3f41-4d1f-bac3-3a5d5b71d100)

**October 2023** - Currently providing awesome services at Valley High and plans on discussing experiences with the high school students and the world of cybersecurity they dove into. Notes and lecture material was also used in this working experience as well created by myself in powerpoint and site form
