### ISSUE TITLE
Albert's Tasks 1/16/23 - 1/20/23

### ISSUE THREAD

**Issue by liluzibird** [natt96z/cybersac#19]

**Comment by natt96z** [comment]
Comment and click "close issue" when Milestone/Issue is fixed

**Comment by liluzibird** [comment]
![image](https://user-images.githubusercontent.com/57073805/213593937-73465e2c-0b14-4114-8782-867c07ba1f2f.png)

**Comment by liluzibird** [comment]
![image](https://user-images.githubusercontent.com/57073805/213594045-43f63710-7656-46e2-8222-09780b37247d.png)

**Comment by liluzibird** [comment]
VMs finished

**Comment by liluzibird** [comment]
Milestones created, as shown

**Comment by liluzibird** [comment]
Spell check and documentation checked, can be verified in change logs

**Comment by liluzibird** [comment]
Pretty much finished everything
