### ISSUE TITLE
Patrice's Tasks  2/13/23 - 2/24/23 

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#30]
*Work on Photoshop/Illustrator Flyer Additions 
*Involve Quiz Questions (v2)
*Spellcheck Newly added material
*Help with CyberSAC Flyer

**Comment by natt96z** [comment]
[cyber_2.zip](https://github.com/natt96z/cybersac/files/10733231/cyber_2.zip)

**Font for CyberSAC Poster - Can be used on Photoshop/Illustrator**

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/220752216-a16ea348-3da6-41a2-8f04-bc46250db8e8.png)

**Comment by natt96z** [comment]
@computerbluerain really good edits! thanks so much!

**Comment by computerbluerain** [comment]
Hi Nate,

Attached is a copy and a paste of DonBot for you to place on the lower left
hand side of the flyer. We can have a discussion in this Friday's meeting
on the final draft and close it out. I hope this meets the requirements for
the flyer.

I wasn't sure if I should have placed this in Elements. I saw another
person's name Luis and is he a part of our chat? Please let me know.

Thanks!

Best Regards,
Patrice

[image: DonBotWithShield5AndTitle.jpg]

**Comment by computerbluerain** [comment]
Hi Nate,

Thank you so much!

Best Regards,

Patrice

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/221266508-fd6a306b-e663-41f0-bd58-a191aef264d2.png)

Very cool!

**Comment by computerbluerain** [comment]
2/13/23 - Started working on Donbot by deconstructing it.
![CyberPatriotLogo1b](https://user-images.githubusercontent.com/116924471/221272709-4a4f26a8-f270-487e-8c6e-892a46235927.jpg)

2/13/23 - Beginner Easy CyberSAC.rst-EasyPatriot
Line - 69   - ** Core Knowledge** - inserted hyphen.
Line - 78   - Malware program, that; settings; Take out comma after websites.
Line - 80   - add comma's to - ,typically,
Line - 84   - language, ….programs, such as … - added comma's.
Line - 104 - Ahead? 2nd sentence - change "A head of starting to encrypt" to "Before it starts to  encrypt,".
Line - 108 - ".exe," - added comma.
Line - 112 - period after account ".", with which? Leave "with" out.
Line - 114 - Gameover, effectively, bypass "with which" to "in which".

2/14/23 - Cleaned up Donbot and cleared all blemishes.
![PictureRobot2](https://user-images.githubusercontent.com/116924471/221240154-0106ebc9-eae8-4bf7-984e-9d1e816b16df.jpg)

2/14/23 - Cleaned up Donbot. Added more color to the chest area to hide the white triangular shape and cleared all blemishes.
![DonBotWithShield copy](https://user-images.githubusercontent.com/116924471/221280183-019d1d56-3041-4d93-94fb-5dc4c838bf39.jpg)

2/14/23 - Beginner Easy CyberSAC.rst-EasyPatriot
Line - 118 - devices, relies on Flash updates..... - added comma.
Line - 130 - Have, unintentionally, downloaded - added comma's.
Line - 142 - individuals, - via ….. interactions - , into - added comma's.
Line - 151 - feature, such as, the - added comma's.
Line - 162 - changes, until - added comma.
Line - 186 - applications, using - take out comma.
Line - 191 - Online Safety - Phishing - created space between "Safety" and "-".
Line - 214 - between "an" to "a" Phishing  - removed the letter "n" off of the word "an".

2/15/23 - Search surroundings on the Shield for cutting out and cleared all blemishes. 
![ShieldBeforeCuttingOut](https://user-images.githubusercontent.com/116924471/221275222-22dfcc97-0fa7-4776-affc-37e69403f747.png)

2/15/23 - Beginner Easy CyberSAC.rst-EasyPatriot
Line - 214 - and "-" a legitimate - closed  space between  the 2 words.
Line - 214 - separate the words "a" and "legitimate form".
Line - 222 - add capital "T" to the word "he" at the beginning of the 2nd sentence.
Line - 222 - place comma after extension, and after filtering - on 2nd sentence.
Line - 229 - Origin "." - "It"

2/16/23 - Continued to work on clearing up the the Shield for cutting out and cleared all blemishes. 
![Working on Shield](https://user-images.githubusercontent.com/116924471/221277141-5abbe217-26f5-47c2-846a-5e8ca82ee696.jpeg)

2/16/23 - Beginner Easy CyberSAC.rst-EasyPatriot
Line - 247 - removed comma - "," after years. removed the word "this" and "is".
Line - 247 - 1st sentence modified the word from "of" to "for" leaked users....
Line - 247 - Correct the word "masive" to "massive".
Line - 247 - placed comma after repository - placed comma after passwords on 1st line.
Line - 247 - "First" is changed to "first - on 2nd line.
Line - 247 - placed comma before and after "usually".
Line - 281 - ..raw:html - not showing on the website??

2/17/23 - Continued to work on clearing up the the Shield for cutting out and cleared all blemishes. 
![SACCyberCenterImage](https://user-images.githubusercontent.com/116924471/221277483-27b0133b-15e6-4fc2-a6d4-907ed885361d.png)

2/17/23 - Finally, cut Shield out of photo. Still working on cleaning it up and refining the shape and size.
![SACCyberCenterImage](https://user-images.githubusercontent.com/116924471/221278014-2fce5def-dc33-4a17-94bf-47400fbc5ec0.png)

2/21/23 - Working on placing the Shield in front of Donbot and measuring its placement. 
![DonBotAndShield copy](https://user-images.githubusercontent.com/116924471/221278316-09bac5ea-ae1b-4999-9164-71e477273d4a.jpg)

2/21/23 - Placing Shield in front of Donbot and measuring how far up or down for its placement. 
![DonBotWithShieldInFront copy800x500](https://user-images.githubusercontent.com/116924471/221278692-ed5d0b1c-2028-4f92-b1f5-6aa7ec9a2c5c.jpg)

2/22/23 - Beginner Easy CyberSAC.rst-EasyPatriot
Line - 283 - <div class="involveme-embeded data-project = "new-project-3849"> - not showing on the website??
Line - 283 - <script src="https://cybersac.involve.me/embed"><script><1dir> - not showing on the website??
Line - 285 -  End of Spelling and Grammar corrections.

2/22/23 - Placing Text on the sides of Donbot and measuring how far up or down on each side to center them. 
2/22/23 - Utilizing the font, "CYBER".
![CYBER font](https://user-images.githubusercontent.com/116924471/221282483-be2bcdab-27fc-4c89-b6f7-c78626690dd8.jpg)

2/22/23 - Worked on getting Element and Fluffy to work on my laptop and cell phone.

2/23/23 - First Final Draft - continued to work on Donbot and its fingers. Should fingers appear or does it looks as if Donbot is 2/23/23 - holding the Shield. Is it too far into chest?
![DonBotWithShield](https://user-images.githubusercontent.com/116924471/221279594-8c09e001-49de-4d41-aded-ede4b14f2936.jpg)

2/23/23 - Discuss First Draft during meeting. Donbot with Title and Shield
![DonBotWithShield5AndTitle](https://user-images.githubusercontent.com/116924471/221283869-ed49814c-9315-49b9-be8e-2f4656bf122a.jpg)

**Comment by computerbluerain** [comment]
Thank you!

**Comment by computerbluerain** [comment]
Good Morning Nate,


Please check for any discrepancies. I, also, have it attached as well. Some
of it is, possibly not in order. You will know what's in order and what's
not.

Best Regards,

Patrice Terrell




February 25, 2023

12:00PM-2:00PM

Today’s Mentor Training _ Linux

Preparation Is Key!

1. Register for training with un: and pw.

2.VM downloads slow? – Download my Linux to students

3. Share VM on the Screen – Split Screen to show Linux Frame and PowerPoint.

4. Create a PowerPoint and create an Introduction – A colorful one!

5. Start my session – Start talking to the students – Have an Introduction
Speech ready!

6. Go over the commands and per PowerPoint slide.

7. Do a Demonstration!

8. Difference between – Ask what is the difference between questions! Users
and Permissions!

9. Make some files.

10 What sort of commissions – Follow the Slides!

11. “Good Afternoon Everyone” – Speak on Intro for Linux! – Explain How
Linux Works! – Create a Linux Frame with un: and pw: (Example); Add a user
to the computer – Is it Case Sensitive?

12. Never assign a User unless they have the Computer Skillset.

13. Switch Users!

14. Expand on how to build (Create It) a Frame and tell how to Brake It
Back Down!

15. If there are any technical difficulties -Then State That!

16. List out all the System Services and Re-Install if needed.

17. Reset Password if needed!

18. Describe what is SSH and is it configured for Password.

19. Show and Teach how to Modify SSH!

20. Ask this question – Do I need a Pseudo permission?

21. Do not need a Pseudo permission when signed in CyberPatriot on live.
They are pseudo approved.

22. Tell them to  -  Update – Then -  Upgrade it – Always!

23. Check Windows for Firewall!

24. What is Ping? Man? Man SSH? H-Top? Install NeoFetch?

25. What is Snap Compository? VLC? Pseudo?

26. Command Practice – Learn and Practice *All *Commands!

27. Ctrl “D” – Enter for cot-test.txt -  “I Am Using Ubuntu!

28. Near the end of the meeting – Talk about Market Shares for Linux – and
how many companies are using Linux!

29. Check all of the Slides – Colors with Words. Make sure your Slides are
Readable!

30. What is Braking? What is Configure? Or Configuration?

31. What is Group Policy for Linux? What is Kernal? What is Terminal? What
is Fedora? What is a Librae Office?

32. Teach in a Basic VM.

33. Before Class is over, make this statement:

*We’re All Just Learning Here! Let’s Just Stick To the Current Slide! Thank
You!*

*For More Information, Join Our CyberPatriot’s Mentor Program!*
