### ISSUE TITLE
Albert's Task 3/6/2023 - 3/10/2023:

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#36]
*Milestone Manager
*Complete any necessary edits on .RST pages
*Collaborate on student teaching ideas
*Personal training sessions (Group)

**Comment by liluzibird** [comment]
![image](https://user-images.githubusercontent.com/57073805/224445191-6459c7f8-9ae2-4061-bc32-e054e6e6f8d7.png)

**Comment by liluzibird** [comment]
Collaborated and helped with CyberPatriots presentation

**Comment by liluzibird** [comment]
Open source translation API
https://github.com/LibreTranslate/LibreTranslate
https://libretranslate.com/?source=auto&target=es&q=Hello
