### ISSUE TITLE
Patrice's Task 3/6/2023 - 3/10/2023:

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#37]
*Logo top banner main .RST page 
*Complete any necessary edits on .RST pages
*Personal training sessions (Group)
*Collaborate on student teaching ideas

**Comment by computerbluerain** [comment]
3/6/2023 - Preparation Is Key! Collaborating on Student Teaching Ideas - Works are still in progress.
[Preparation Is Key!.docx](https://github.com/natt96z/cybersac/files/10946396/Preparation.Is.Key.docx)

3/7/2023 - Banner with DonBot - DonBot on Top or Bottom of Banner Logo - Works are still in progress.
![BannerWithDonBotTop copy](https://user-images.githubusercontent.com/116924471/224435731-f40d9cda-9b9c-4a80-a014-8019806bf981.jpg)
![BannerWithDonBotBottom copy](https://user-images.githubusercontent.com/116924471/224435776-8adf0354-4a24-4fb3-b8f8-3836323eb165.jpg)

3/8/2023 - Spelling and Grammar Correction Updates - Works are still in progress.
Line - 67 - comma before and after easily.
Line - 69 - comma before own.
![67-69](https://user-images.githubusercontent.com/116924471/224439026-b82c0cd4-89fe-40d4-b780-24d8669770e9.jpg)


3/9/2023 - Spelling and Grammar Correction Updates - Works are still in progress.


3/10/2023 - Personal Training Sessions (Group) - Attended the CyberPatriot session for students to tour and enter the program 
![Training Session3-10-2023]

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/224445097-aec65921-1b81-4043-a2df-5b877d0a9c29.png)

**Comment by natt96z** [comment]
[Attended Student Presentation 3-10-2023]
![image](https://user-images.githubusercontent.com/112590005/224445185-43d430e4-eeec-462a-839f-d96097c416e3.png)
