### ISSUE TITLE
Patrice's Task 3/13/2023 - 3/17/2023:

### ISSUE THREAD

**Issue by liluzibird** [natt96z/cybersac#40]
*Complete any necessary edits on .RST pages
*Promote CyberPatriots
*Personal training sessions (Group) - Includes Document Noted
*Adding images
*Enhancing images

**Comment by computerbluerain** [comment]
3/13/2023 - First Draft for the "Welcome to the Official Santa Ana College CyberPatriot Documentation Hub!" page.
![BannerAndLogoWithChanges1 copyLighter](https://user-images.githubusercontent.com/116924471/226058444-7f304e9a-c5ac-4226-921b-38fff0d5181f.jpg)

3/13/2023
Line – 44 – comma after HTTP
Line – 44 – 3rd Line – comma after HTTPS
Line – 65 – comma after encrypted 
Line – 65 - the word “and” is removed
Line – 67 – comma before and after easily
Line – 69 – comma after own
Line - 78 – comma virus
Line – 78 – comma usually
Line – 78 – comma is removed after malicious
Line - 90 – comma infectors,
Line - 90 – comma after itself
Line - 92 – comma after file
Line - 108 – comma emails

3/14/2023 - Worked on DonBot upper and lower body features.
![DonBotCompletedUpdate2TopHalf copy](https://user-images.githubusercontent.com/116924471/226058835-cf59fc07-41a2-41ea-9ae4-3321f7e54296.jpg)
![WaistDownMovableSkinnyRobot copy](https://user-images.githubusercontent.com/116924471/226059031-4bbb7dcf-038b-42cb-9374-d58eda571fe3.jpg)

3/14/2023
Line – 112 – space entered after legitimate – 
Line – 112 – “with” and “to” are removed
Line – 112 – “steal” is now “steals”
Line – 114 – comma after that, the
Line – 114 – comma after that, it
Line – 138 - comma before and after effectively
Line - 151 – comma after manager
Line - 176 – comma after anything
Line - 186 - comma after holes
Line - 186 - comma after application
Line - 186 - comma after protection

3/15/2023 - worked on fusing DonBot body together along with shield.
![Full Size Half And Half Skinny Robot And DonBot copy](https://user-images.githubusercontent.com/116924471/226059293-a9a6dd02-2b6b-44cd-b613-000a0fa1e284.jpg)
![FullRobot1 copy](https://user-images.githubusercontent.com/116924471/226059242-cfb29e7f-8b27-4a07-8f39-032a453dd7e7.jpg)

3/15/2023
Line - 214 - comma after difference
Line - 214 - comma after communication
Line - 214 - comma after emails
Line - 214 - comma after inbox
Line – 255 - comma after especially
Line - 256 – 2nd Line –“hack” is changed to “hat”
Line – 256 – 3rd Line – comma is before and after regularly
Line – 265 – comma after frequently
Line – 265 – 3rd Line -  comma after occasionally
Line – 265 – 3rd Line - comma after Usually
Line – 265 – 4th Line – comma after thing
Line – 274 – comma before and after intentionally
Line – 274 – 2nd Line – comma before and after as well
Line – 274 – 2nd Line – inserted the word “and”
Line -274 – 3rd Line – changed “speady” to “spreading”
Line – 274 – comma before and after information

3/16/2023 - Searched for a right hand and placed the hand, along with a patch on wrist for DonBot.
![New Right Hand Up copy](https://user-images.githubusercontent.com/116924471/226059539-47a26c16-bcf4-45dd-90ec-aaf4d505bb98.jpg)

3/16/2023 - Created the complete DonBot with new hand and legs.
![CompletedMovableDonBot copy](https://user-images.githubusercontent.com/116924471/226059750-9788ab86-8448-4e9e-85d0-277d306cb18d.jpg)

3/16/2023 -  Worked in Illustrator and Exported to Photoshop, within the Web and created DonBot waving to all future students that are interested in the CyberSAC CyberPatriot Program.
![DonBotAnimatedGif](https://user-images.githubusercontent.com/116924471/226059898-5332a2a8-e60f-47bf-ade2-28f4e4a78332.gif)
