### ISSUE TITLE
Nate's Task 3/13/2023 - 3/17/2023:

### ISSUE THREAD

**Issue by liluzibird** [natt96z/cybersac#41]
*Complete any necessary edits on .RST pages
*Promote CyberPatriots
*Personal training sessions (Group)
*Windows10
*Linux
*Programming
*Enhancements for webpage
*Fix quiz implementation - Show right and wrong results.

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/225177750-3acff8ac-98c3-45fb-a659-d6ca0703f96a.png)

![image](https://user-images.githubusercontent.com/112590005/225181759-057715d1-a32f-49df-8b27-06c6db2553c9.png)


**_Involve.me:_** March 13th - Quiz's show right and wrong immediately including end score, fixing response text as well. Multiple selection answers seem to not allow showing incorrect selections.

**Comment by natt96z** [comment]
![BannerAndLogoWithChanges](https://user-images.githubusercontent.com/112590005/225183299-27cf808e-c0b0-4df9-8adf-1896ad75c170.png)

![image](https://user-images.githubusercontent.com/112590005/225183369-4534f6b1-06a2-49f8-b568-cf7341ef3da1.png)


**_PhotoShop/Krita - Banner Work_**: March 14th - Working on the top banner material Patrice sent me via email. I decided to upscale the bottom banner PSD area as well.

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/225846461-258e3ec2-38a8-4380-94da-ef9d28117061.png)

**_Student Feedback - Admins/Collaborators_** - March 15th: Feedback Admin/Collaborators Added for CyberSAC feedback responses from students, Admin link available in links area and by request. There has so far only been minor responses. 

![Screenshot from 2023-03-14 18-15-24](https://user-images.githubusercontent.com/112590005/225846912-50e08cc1-20a7-4867-9e0f-c90bd3dea897.png)

**_ReadTheDocs New Rule - PDF Formatting_** - March 15th: Such a disappointing change but a new necessary rule, site will not build/publish if PDF is defective in any way, PDF implementation has been temporarily disabled till I can find a correct way to modify Lumache theme image wrapping.

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/225889036-ba76ada2-441e-459d-bd38-e828e5a0d1d6.png)

**_News Page In Development - Probably Finished [Completed added to main index.rst] - March 16th:_ (RSS to HTML)** This page combines (sign up) the already provided CyberCentinel and ADJUSTABLE news source that can be changed, but I chose The Hacker News and Trend Micro. the RST will be published tomorrow on the 17th.

**Comment by natt96z** [comment]
![image](https://user-images.githubusercontent.com/112590005/226033374-3c5cac11-2e89-46cd-bc98-21722fe105d1.png)

**_Complete any necessary edits on .RST pages - Build Succesful - March 17th:_** Understandably the PDF issue is still ongoing, all improvements to the page have been made. News page is adjustable, feedback page is ongoing with new submissions.
