### ISSUE TITLE
Patrices Task 5/15/2023 - 5/19/2023

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#67]
* Brainstorm next meeting idea - organizational skills, skills for all, computer configuration
* Review student feedback from the meeting - Team members got in-person feedback
* Provide new "Minutes of the Meeting" as well as add new videos and image content for CyberSAC
* Research/Work on Virtual Machine environments (Notes, brainstorm ideas, make practice machines)

**Comment by computerbluerain** [comment]
Patrice Terrell’s Tasks for 5/15/2023 – 5/19/2023

5/16/2023 - Group Collaboration Zoom Meeting – May 16, 2023, Tuesday @ 2:30 PM

•	Brainstorm next meeting idea - organizational skills, skills for all, computer configuration
•	Review student feedback from the meeting - Team members got in-person feedback
•	Discussed Additional Eye Candy for new students based on their view of the website
•	(Patrice, Nate, and Angel)

5/17/2023 

•	Provide new "Minutes of the Meeting" as well as add new videos and image content for CyberSAC

5/18/2023

•	Research/Work on Virtual Machine environments (Notes, brainstorm ideas, make practice machines)
•	Continued Work On New Minutes of the Meeting
•	Additional Tasks – Spelling, Grammar on Github.rst.

5/19/2023 – CyberPatriot Meeting at Santa Ana College, Friday, May 19, 2023, 3:00 PM
![Programs_Dept-ComputerScience_lrg_0](https://github.com/natt96z/cybersac/assets/116924471/bc416322-a224-48e6-8afb-b1a7dbcb74c8)
