### ISSUE TITLE
Angels Task 6/20/2023 - 6/23/2023

### ISSUE THREAD

**Issue by natt96z** [natt96z/cybersac#83]
*Work on Cisco Material 
*Meeting Wensdays/Collaboration
*Necessary edits to RST pages
*Add virtual packet tracer tool to website
*Work on lab script

**Comment by OdyTro** [comment]
merged and completed SSH, Routing Tables, and HTTP web server labs

![lol4](https://github.com/natt96z/cybersac/assets/132408550/c4428ca5-9147-4eb7-afba-fe3efc36da4f)

**Comment by OdyTro** [comment]
Enrolled in Cisco courses. Completed 1.
![lol3](https://github.com/natt96z/cybersac/assets/132408550/b87051ef-8dd4-4120-a7ac-af2ad5126167)

**Comment by OdyTro** [comment]
Templates for both base and finished PTK files.

![lol5](https://github.com/natt96z/cybersac/assets/132408550/8a494241-ed0e-445f-a9ca-f8ad99ca4dda)
